[platformio]
default_envs = breath-pet
core_dir = .cache/platformio

[env:breath-pet]
platform = espressif32@6.5.0
board = lilygo-t-display-s3
framework = arduino
upload_protocol = esptool
upload_speed = 921600
monitor_speed = 115200
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DDISABLE_ALL_LIBRARY_WARNINGS
